### ISSUE TITLE
clock.syncTime() returns undefined

### ISSUE THREAD

**Issue by amitsystech** [artem-russkikh/react-native-clock-sync#1]

**Comment by artem-russkikh** [comment]
`clock.syncTime()` just forces synchronization process and doesnt return anything: https://github.com/artem-russkikh/react-native-clock-sync/blob/master/index.js#L43

Also it calls automatically in interval every `tickRate` ms  here: https://github.com/artem-russkikh/react-native-clock-sync/blob/master/index.js#L29 when JS thread is active (not in background)
